### ISSUE TITLE
Client cannot connect to server, gives no error number

### ISSUE THREAD

**Issue by Noam5** [Martyx00/CollaREServer#1]
I get the following error when connect to the server, I have configured everything correctly as described in the CollaREServer page and can even access the server's URL using the browser 
![image](https://user-images.githubusercontent.com/246069/137907327-3038d2e3-6120-497e-b469-f0866df6d648.png)

**Comment by Martyx00** [comment]
The client does a sort of certificate pinning so the URL in the bar has to match the hostname for which you have created a certificate (test.com for example). 
If you do not have the name resolvable by your local DNS you can add an entry into a host file on your computer. Also make sure that you can reach the hostname via browser for example to rule out possible firewall issues.

**Comment by Martyx00** [comment]
I have updated the client to use more verbose error messages: https://github.com/Martyx00/CollaRE/commit/085f7fa64197af6c5fde36097dbd31f6caffd853
